import sys 
import ijson

# Process the json file generated by the lncli describegraph 
def process_graph(json_file):
# Open the JSON file for reading
    with open(json_file, 'r') as file:
        # Create an iterator for the JSON data
        parser = ijson.parse(file)
    
        # Iterate over each JSON event
        for prefix, event, value in parser:
            # Process each event as needed
            # Print the event type and corresponding data value
            print("prefix:", prefix)
            print("Event:", event)
            print("Data:", value)

    return               # Return hops list and the number of routes > 1 if it is MPP
 
def main(json_file):
    # Load Lightning Network route from CSV file
    process_graph(json_file)

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python nodenamer.py <json_file>")
        sys.exit(1)
    json_file = sys.argv[1]
    main(json_file)

